"""
Script: train.py

Description:
    Standard PyTorch training loop for the ResidualPredictor.
    Loads a dynamically generated regime-specific dataset, trains the 
    Neural Network to predict the 6 Classical Orbital Element (COE) 
    residual errors, and saves the best model weights dynamically.
"""

import os
import torch
import torch.nn as nn
import torch.optim as optim
from ml.dataset         import getDataloaders
from ml.active_learning import ResidualPredictor

def trainModel(csv_file, epochs = 150, batch_size = 512, lr = 1e-3):
    """
    Executes the training and validation loop for the Neural Network.
    Automatically generates the output .pth filename based on the input dataset.
    
    Inputs:
        csv_file   : Path to the training dataset CSV.
        epochs     : Maximum number of training epochs.
        batch_size : Number of samples per batch.
        lr         : Initial learning rate for the Adam optimizer.
    """
    
    # Dynamically determine the model save path based on the CSV filename
    base_name = os.path.basename(csv_file)
    name_without_ext = os.path.splitext(base_name)[0]

    # Replace 'dataset' with 'predictor' for the saved model weights
    model_filename = name_without_ext.replace("dataset", "predictor") + ".pth"
    model_save_path = f"models/{model_filename}"

    print("=" * 70)
    print(f"🧠 STARTING NEURAL NETWORK TRAINING (EXPERT REGIME)")
    print(f"   Input Dataset : {csv_file}")
    print(f"   Output Model  : {model_save_path}")
    print("=" * 70)
    
    # 1. Load Data
    if not os.path.exists(csv_file):
        raise FileNotFoundError(f"Dataset not found at {csv_file}. Run generate_dataset.py first.")
        
    train_loader, val_loader, dataset = getDataloaders(csv_file, batch_size = batch_size)
    print(f" [INFO] Training samples: {len(train_loader.dataset)} | Validation samples: {len(val_loader.dataset)}\n")
    
    # 2. Initialize Network, Loss Function, and Optimizer
    model = ResidualPredictor()
    criterion = nn.MSELoss()  

    # L2 Regularization (weight_decay) included to prevent overfitting
    optimizer = optim.Adam(model.parameters(), lr = lr, weight_decay = 1e-5)
    
    # Learning Rate Scheduler: Reduces LR by half if Val Loss plateaus for 5 epochs
    scheduler = optim.lr_scheduler.ReduceLROnPlateau(optimizer, mode = 'min', factor = 0.5, patience = 5)
    
    best_val_loss = float('inf')
    os.makedirs("models", exist_ok = True)
    
    # 3. Epoch Loop
    for epoch in range(epochs):
        # --- TRAINING PHASE ---
        model.train()
        train_loss = 0.0
        
        for batch_X, batch_Y in train_loader:
            optimizer.zero_grad()                  # Clear old gradients
            predictions = model(batch_X)           # Forward pass
            loss = criterion(predictions, batch_Y) # Compute error
            loss.backward()                        # Backward pass
            optimizer.step()                       # Update weights
            
            train_loss += loss.item() * batch_X.size(0)
            
        train_loss /= len(train_loader.dataset)
        
        # --- VALIDATION PHASE ---
        model.eval()
        val_loss = 0.0
        
        with torch.no_grad(): # Disable gradient calculation for validation
            for batch_X, batch_Y in val_loader:
                predictions = model(batch_X)
                loss = criterion(predictions, batch_Y)
                val_loss += loss.item() * batch_X.size(0)
                
        val_loss /= len(val_loader.dataset)
        
        # Update the scheduler with the current validation loss
        scheduler.step(val_loss)
        
        # 4. Save the best model dynamically
        saved_mark = ""
        if val_loss < best_val_loss:
            best_val_loss = val_loss
            torch.save(model.state_dict(), model_save_path)
            saved_mark = "(*)" # Mark to indicate a new best model was saved
            
        # 5. Print progress every 10 epochs
        if (epoch + 1) % 10 == 0 or epoch == 0:
            print(f" Epoch {epoch+1:03d}/{epochs} | Train Loss: {train_loss:.4f} | Val Loss: {val_loss:.4f} {saved_mark}")
            
    print(f"\n✅ Training complete. Best expert weights saved to '{model_save_path}'")


# =============================================================================
# Execution Block
# =============================================================================
if __name__ == "__main__":
    # Define the specific target dataset generated by generate_dataset.py
    target_csv = "data/orbita_dataset_300-2000_0-0.1_0-0.csv"
    
    trainModel(csv_file = target_csv)